### ISSUE TITLE
Time.h and time.h issue on windows

### ISSUE THREAD

**Issue by mars000** [PaulStoffregen/Time#159]
because esp32 already has a built in time.h it gets confused with Time.h as it does not recognize cases.
can the developer pls fix this issues once and for all so it works correctly on windows os ?

**Comment by blackketter** [comment]
Use `#include "TimeLib.h"` instead.

**Comment by PaulStoffregen** [comment]
Sadly, this is confirmation we *still* have a lot of code in the wild which includes Time.h.  :-(

**Comment by PaulStoffregen** [comment]
I am planning to delete Time.h.  That's why Time.h gives a warning to use TimeLib.h.

But this issue is also confirmation that obviously a lot of Arduino users have the default setting where Arduino doesn't show the compiler's warning messages, only errors.

Maybe I'll change the warning to an error and publish a new version.  Hopefully **that** will finally get the remaining Time.h includes changed?

**Comment by PaulStoffregen** [comment]
Ok... done, 1.6.1 release!
